version: "3.3"

services:
  fiasuite-core:
    image: fiasuitecore
    build:
      context: ../..
      dockerfile: docker/Dockerfile

    ports:
      - "8000:8000"

networks:
  default:
    external: true
    name: fiasuite-network